CREATE DATABASE FACE_CHECK
GO

USE FACE_CHECK

CREATE TABLE TIPOUSUARIO(
	idTipoU TINYINT PRIMARY KEY IDENTITY,
	nomeTipoU VARCHAR(70) UNIQUE NOT NULL
);
GO

CREATE TABLE USUARIO(
	idUsuario SMALLINT PRIMARY KEY IDENTITY,
	idTipoU TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoU),
	nomeUsuario VARCHAR(100) NOT NULL,
	email VARCHAR(256) NOT NULL,
	senha VARCHAR(18) NOT NULL CHECK(len(senha)>= 8)
);
GO

CREATE TABLE PERIODOS(
	idPeriodo INT PRIMARY KEY IDENTITY,
	nomePeriodo VARCHAR(20) UNIQUE NOT NULL,
);
GO

CREATE TABLE SALAS(
	idSala INT PRIMARY KEY IDENTITY,
	idPeriodo INT FOREIGN KEY REFERENCES PERIODOS(idPeriodo),
	nomeSala VARCHAR(15) UNIQUE NOT NULL
);
GO

CREATE TABLE ALUNOS(
	idAlunos INT PRIMARY KEY IDENTITY,
	idSala INT FOREIGN KEY REFERENCES SALAS(idSala),
	nomeAluno VARCHAR(200) NOT NULL,
	dataNascimento DATETIME NOT NULL,
	RA CHAR(7) NOT NULL,
	imagem VARCHAR(255)
);
GO